apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-worker-deployment
  labels:
    app: python-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-worker
  template:
    metadata:
      labels:
        app: python-worker
    spec:
      containers:
        - name: python-worker
          image: aivora017/devops-python-worker:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 5000
          env:
            - name: GO_API_URL
              value: "http://go-api-service:80"
          